### ISSUE TITLE
Yogesh Tracker

### ISSUE THREAD

**Issue by christopherreay** [christopherreay/thisEqualsThat_frontEnd#23]
- [ ] Dimensions of the crate
- [ ] Zoom Control Improvements
- [ ] Integrate frame of reference
  - [ ] Cat
  - [ ] Girl (hi def)
